[package]
name = "doco"
version = "0.1.1"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/gloridifice/doco"
homepage = "https://github.com/gloridifice/doco"

description = "File-backed change management for coding agents"
rust-version = "1.85"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
console = "0.16"
fs2 = "0.4"
pulldown-cmark = "0.13"
regex = "1"
similar = "2"
tempfile = "3"
time = { version = "0.3", default-features = false, features = [
    "std",
    "parsing",
    "formatting",
] }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = [
    "Win32_Storage_FileSystem",
    "Win32_Foundation",
] }
